#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Varg Matrix Agent - Setup Script
#
# Bootstraps the full stack:
# 1. Configures Element Web for the target server
# 2. Starts Conduit (Matrix homeserver)
# 3. Waits for Conduit readiness
# 4. Registers the agent account
# 5. Starts the remaining services
#
# Usage:
#   ./setup.sh                          # Interactive setup
#   ./setup.sh --server-name 1.2.3.4    # Non-interactive with IP
#   ./setup.sh --server-name example.com # Non-interactive with domain
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --- Default Configuration ---
SERVER_NAME="${SERVER_NAME:-}"
MATRIX_USERNAME="${MATRIX_USERNAME:-varg-agent}"
MATRIX_PASSWORD="${MATRIX_PASSWORD:-}"
VARG_LLM_PROVIDER="${VARG_LLM_PROVIDER:-ollama}"
DEV_MODE="${DEV_MODE:-true}"

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
    case $1 in
        --server-name) SERVER_NAME="$2"; shift 2 ;;
        --username)    MATRIX_USERNAME="$2"; shift 2 ;;
        --password)    MATRIX_PASSWORD="$2"; shift 2 ;;
        --llm)         VARG_LLM_PROVIDER="$2"; shift 2 ;;
        --prod)        DEV_MODE="false"; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# --- Interactive Setup ---
if [ -z "$SERVER_NAME" ]; then
    echo "=== Varg Matrix Agent Setup ==="
    echo ""
    read -p "Server name (IP or domain) [localhost]: " SERVER_NAME
    SERVER_NAME="${SERVER_NAME:-localhost}"
fi

if [ -z "$MATRIX_PASSWORD" ]; then
    MATRIX_PASSWORD=$(openssl rand -base64 24 2>/dev/null || echo "varg-agent-$(date +%s)")
    echo "Generated agent password: $MATRIX_PASSWORD"
fi

echo ""
echo "Configuration:"
echo "  Server:   $SERVER_NAME"
echo "  Username: $MATRIX_USERNAME"
echo "  LLM:      $VARG_LLM_PROVIDER"
echo "  Mode:     $([ "$DEV_MODE" = "true" ] && echo "Development" || echo "Production")"
echo ""

# --- Configure Element Web ---
echo "[1/5] Configuring Element Web..."

if [ "$DEV_MODE" = "true" ]; then
    CONDUIT_PORT="${CONDUIT_PORT:-6167}"
    HOMESERVER_URL="http://${SERVER_NAME}:${CONDUIT_PORT}"
else
    HOMESERVER_URL="https://${SERVER_NAME}"
fi

# Update Element config with actual server URL
sed -e "s|HOMESERVER_URL_PLACEHOLDER|${HOMESERVER_URL}|g" \
    -e "s|SERVER_NAME_PLACEHOLDER|${SERVER_NAME}|g" \
    element/config.json > element/config.json.tmp
mv element/config.json.tmp element/config.json

echo "  Element configured for: $HOMESERVER_URL"

# --- Write .env file ---
echo "[2/5] Writing environment file..."

cat > .env <<EOF
# Varg Matrix Agent - Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

SERVER_NAME=${SERVER_NAME}
MATRIX_USERNAME=${MATRIX_USERNAME}
MATRIX_PASSWORD=${MATRIX_PASSWORD}

# LLM Configuration
VARG_LLM_PROVIDER=${VARG_LLM_PROVIDER}
VARG_LLM_MODEL=${VARG_LLM_MODEL:-}
VARG_LLM_URL=${VARG_LLM_URL:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}

# Agent Configuration
AGENT_DISPLAY_NAME=${AGENT_DISPLAY_NAME:-Varg Agent}
AGENT_AUTO_JOIN=true
ALLOW_FEDERATION=false

# Ports (dev mode)
CONDUIT_PORT=${CONDUIT_PORT:-6167}
ELEMENT_PORT=${ELEMENT_PORT:-8080}
HTTP_PORT=${HTTP_PORT:-80}
HTTPS_PORT=${HTTPS_PORT:-443}
EOF

echo "  .env written"

# --- Start Conduit ---
echo "[3/5] Starting Conduit homeserver..."

COMPOSE_CMD="docker compose"
if [ "$DEV_MODE" = "true" ]; then
    COMPOSE_CMD="docker compose -f docker-compose.yml -f docker-compose.dev.yml"
fi

$COMPOSE_CMD up -d conduit
echo "  Conduit starting..."

# --- Wait for Conduit ---
echo "[4/5] Waiting for Conduit to be ready..."

CONDUIT_INTERNAL="http://localhost:${CONDUIT_PORT:-6167}"
MAX_WAIT=60
WAITED=0

while ! curl -sf "${CONDUIT_INTERNAL}/_matrix/client/versions" > /dev/null 2>&1; do
    sleep 2
    WAITED=$((WAITED + 2))
    if [ $WAITED -ge $MAX_WAIT ]; then
        echo "  ERROR: Conduit did not start within ${MAX_WAIT}s"
        echo "  Check logs: $COMPOSE_CMD logs conduit"
        exit 1
    fi
    echo "  Waiting... (${WAITED}s)"
done

echo "  Conduit is ready!"

# --- Register Agent Account ---
echo "[5/5] Registering agent account..."

REGISTER_BODY=$(cat <<ENDJSON
{
    "username": "${MATRIX_USERNAME}",
    "password": "${MATRIX_PASSWORD}",
    "auth": {"type": "m.login.dummy"},
    "initial_device_display_name": "Varg Agent Setup"
}
ENDJSON
)

REGISTER_RESULT=$(curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "$REGISTER_BODY" \
    "${CONDUIT_INTERNAL}/_matrix/client/v3/register" 2>&1) || true

if echo "$REGISTER_RESULT" | grep -q "access_token"; then
    echo "  Agent account '${MATRIX_USERNAME}' registered successfully"
elif echo "$REGISTER_RESULT" | grep -q "M_USER_IN_USE"; then
    echo "  Agent account '${MATRIX_USERNAME}' already exists"
else
    echo "  Registration response: $REGISTER_RESULT"
    echo "  (Agent will try to login with existing credentials)"
fi

# --- Start Remaining Services ---
echo ""
echo "Starting all services..."
$COMPOSE_CMD up -d

echo ""
echo "=== Setup Complete ==="
echo ""
if [ "$DEV_MODE" = "true" ]; then
    echo "Access:"
    echo "  Element Web:  http://${SERVER_NAME}:${ELEMENT_PORT:-8080}"
    echo "  Matrix API:   http://${SERVER_NAME}:${CONDUIT_PORT:-6167}"
else
    echo "Access:"
    echo "  Element Web:  https://${SERVER_NAME}"
    echo "  Matrix API:   https://${SERVER_NAME}/_matrix/"
fi
echo ""
echo "  Agent user:   @${MATRIX_USERNAME}:${SERVER_NAME}"
echo "  Agent pass:   ${MATRIX_PASSWORD}"
echo ""
echo "Next steps:"
echo "  1. Open Element Web and register a user account"
echo "  2. Start a direct chat with @${MATRIX_USERNAME}:${SERVER_NAME}"
echo "  3. Send a message - the agent will respond!"
echo ""
echo "Logs: $COMPOSE_CMD logs -f"
